// ═══════════════════════════════════════════════════════════════════════
//  CABINETZONE — PORTFOLIO DATA
//  Auto-generated by: node scan-photos.mjs
//
//  HOW TO ADD CONTENT:
//
//  New photo in an existing project:
//    → Drop the image into the project's folder
//    → Run: node scan-photos.mjs
//
//  New project:
//    → Create a subfolder inside a category folder
//    → Name it with hyphens:  e.g.  modern-open-kitchen
//    → Add cover.jpg + any detail photos (01.jpg, 02.jpg, ...)
//    → Run: node scan-photos.mjs
//
//  New category:
//    → Create a new folder inside brand_assets/projects/
//    → Add project subfolders inside it
//    → Run: node scan-photos.mjs
//    → A new tab appears on the portfolio page automatically
//
//  FOLDER STRUCTURE:
//    brand_assets/projects/
//      kitchen/
//        riverside-modern-kitchen/
//          cover.jpg
//          01.jpg  02.jpg  ...
//      bathroom/
//        heritage-vanity-suite/
//          cover.jpg  01.jpg  ...
//      {new-category}/
//        {new-project}/
//          cover.jpg  ...
// ═══════════════════════════════════════════════════════════════════════

const PROJECTS = [
  {
    "id": 1,
    "cat": "bathroom",
    "label": "Bathroom",
    "title": "Heritage Vanity Suite",
    "cover": "/brand_assets/projects/bathroom/heritage-vanity-suite/cover.jpg",
    "photos": [
      {
        "src": "/brand_assets/projects/bathroom/heritage-vanity-suite/01.jpg",
        "cap": ""
      },
      {
        "src": "/brand_assets/projects/bathroom/heritage-vanity-suite/02.jpg",
        "cap": ""
      }
    ]
  },
  {
    "id": 2,
    "cat": "builtin",
    "label": "Built-Ins",
    "title": "Walnut Library Wall",
    "cover": "/brand_assets/projects/builtin/walnut-library-wall/cover.jpg",
    "photos": [
      {
        "src": "/brand_assets/projects/builtin/walnut-library-wall/01.jpg",
        "cap": ""
      },
      {
        "src": "/brand_assets/projects/builtin/walnut-library-wall/02.jpg",
        "cap": ""
      }
    ]
  },
  {
    "id": 3,
    "cat": "kitchen",
    "label": "Kitchen",
    "title": "Riverside Modern Kitchen",
    "cover": "/brand_assets/projects/kitchen/riverside-modern-kitchen/cover.jpg",
    "photos": [
      {
        "src": "/brand_assets/projects/kitchen/riverside-modern-kitchen/01.jpg",
        "cap": ""
      },
      {
        "src": "/brand_assets/projects/kitchen/riverside-modern-kitchen/02.jpg",
        "cap": ""
      },
      {
        "src": "/brand_assets/projects/kitchen/riverside-modern-kitchen/03.jpg",
        "cap": ""
      }
    ]
  }
];
